apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: helloworld-dest-rule
spec:
  trafficPolicy:
    loadBalancer:
      localityLbSetting:
        enabled: true
        failoverPriority:
        - "app=helloworld"
        - "version=v2"