apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../../base

patches:
- path: patch-ossm3-subscription.yaml
  target:
    group: operators.coreos.com
    kind: Subscription
    name: servicemeshoperator3
    namespace: openshift-operators
    version: v1alpha1
- path: patch-kiali-subscription.yaml
  target:
    group: operators.coreos.com
    kind: Subscription
    name: kiali-ossm
    namespace: openshift-operators
    version: v1alpha1
