apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: istio-system

resources:
  # East-West Gateways are in each overlay
  # Expose Service from E-W Gateway
  - expose-services.yaml

  # Add Regular Ingress Gateway for services to use
  - ingress-gateway.yaml
