apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
  # Inherit base
  - ../../base/
  # East-West Gateway (network2, cluster2, west)
  - east-west-gw-net2.yaml

patches:
  - path: patch-istio-system-namespace-labels.yaml
    target:
      name: istio-system
      kind: Namespace
      version: v1
