apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample

resources:
  # Create the Namespace
  - sample-namespace.yaml
  
  # Deploy curl container
  - curl.yaml

  # Expose helloworld via gateway
  - helloworld-gateway.yaml
  # Expose to outside
  # Create a route to ingressgateway to helloworld
  #- helloworld-igw-route.yaml