apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  
# Create cacerts secret for West
secretGenerator:
  - name: cacerts
    namespace: istio-system
    type: Opaque
    files:
    - ca-cert.pem=./ca-cert.pem
    - ca-key.pem=./ca-key.pem
    - root-cert.pem=./root-cert.pem
    - cert-chain.pem=./cert-chain.pem