apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Istio System Namespace
  - istio-system-namespace.yaml
  # Istio CNI Namespace
  - istio-cni-namespace.yaml

  # Add top banner of cluster name/region
  - top-banner.yaml
